---
title: "Plot Results"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load library

```{r,message=FALSE}
library(tidyverse)
library(broom)
library(Hmisc)
theme_set(theme_bw())
```

To do: 
- Add ensembl gene names to normalized file, modify colnames to indicate species

```{r,message=FALSE}
d <- read_tsv("../../02_Processed/GTEx.v7.all.norm.txt",col_types= cols(ENTREZ = "c"))
```

Add pathways to mean expression scaled file

```{r}
most <- read_tsv("~/Documents/Data/Gene_sets/Shuyang_most_least_conserved/genes_MOST_conserved_exon_191107.txt")  %>% 
  mutate(most_conserved=1) %>% 
  select(geneName,most_conserved) %>% 
  filter(!is.na(geneName))

least <- read_tsv("~/Documents/Data/Gene_sets/Shuyang_most_least_conserved/genes_LEAST_conserved_exon_191107.txt")  %>% 
  mutate(least_conserved=1) %>% 
  select(geneName,least_conserved) %>% 
  filter(!is.na(geneName))
```

```{r}
d <- left_join(d,most)
d <- left_join(d,least)
```


```{r}
d <- mutate(d,log2Expr_sum_mean_scaled1M=log2(Expr_sum_mean_scaled1M+1))
```

```{r}
get_enrichment <- function(pathway){
  pathway_text <- gsub('\\"','',deparse(pathway))
  dfilt <- d[which(d[pathway]==1),]
  dfilt <- dfilt %>% group_by(geneName) %>% mutate(mean_cell_type=mean(log2Expr_sum_mean_scaled1M))
  res <- tidy(lm(log2Expr_sum_mean_scaled1M ~0 + Lvl5+mean_cell_type,data=dfilt)) %>% mutate(term=gsub("Lvl5","",term))
  res <- mutate(res,p.value=ifelse(estimate>0,p.value/2,1-(p.value/2))) %>% arrange(p.value) 
  res <- filter(res,!term%in%c("mean_cell_type","(Intercept)"))
  res <- mutate(res,pathway = capitalize(tolower(gsub("_"," ",pathway))))
}
```

```{r}
order_terms <- function(d){
  ordered_terms <- d %>% group_by(term) %>% summarise(median=median(-log10(p.value))) %>% arrange(median) %>% select(term)
  return(ordered_terms$term)
}
order_pathways <- function(d){
  ordered_pathways <- d %>% group_by(pathway) %>% summarise(mean=mean(-log10(p.value))) %>% arrange(-mean) %>% select(pathway)
  return(ordered_pathways$pathway)
}
wrapit <- function(text) {
  wtext <- paste(strwrap(text,width=20),collapse=" \n ")
  return(wtext)
}
plot_pathways <- function(d,out,height=8,width=14){
  p1 <- ggplot(d,aes(term,-log10(p.value),fill=Significance)) + geom_bar(stat="identity") + coord_flip() + xlab("") + ylab("-log10(pvalue)") + facet_wrap(~pathway,scales = "free_x") 
  ggsave(p1,filename = out,height=height,width=width,limitsize=FALSE)
}
```


```{r,message=FALSE}
pathways <- "most_conserved"
d2 <- get_enrichment(pathways) %>% 
  mutate(term=factor(term,levels=order_terms(.))) %>% 
  mutate(fdr=p.adjust(p.value,method="fdr")) %>%
  mutate(Significance=ifelse(fdr<0.05,"5% FDR", "Not Significant"))
```

# Plot

```{r}
plot_pathways(d2,"../Plots/GTEx/ShuyangConserved/most_conserved.pdf")
write_tsv(d2,"../Plots/GTEx/ShuyangConserved/most_conserved.txt")
```


```{r,message=FALSE}
pathways <- "least_conserved"
d2 <- get_enrichment(pathways) %>% 
  mutate(term=factor(term,levels=order_terms(.))) %>% 
  mutate(fdr=p.adjust(p.value,method="fdr")) %>%
  mutate(Significance=ifelse(fdr<0.05,"5% FDR", "Not Significant"))
```

# Plot

```{r}
plot_pathways(d2,"../Plots/GTEx/ShuyangConserved/least_conserved.pdf")
write_tsv(d2,"../Plots/GTEx/ShuyangConserved/least_conserved.txt")
```