---
title: "gene_set_expression_check"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

# Level 1

```{r}
f <- "/Users/julienbryios/Documents/Data/Projects/Best_tissue2/Data/Dronc-seq/CellTypeData_DroncSeqV2.rda"
```

```{r}
load(f)
exp <- as.data.frame(ctd[[1]]$mean_exp) %>% rownames_to_column("Gene")
```

```{R, load data 3,message=FALSE, warning=FALSE}
exp_lvl5 <- gather(exp,key = Lvl5,value=Expr_sum_mean,-Gene) %>% as_tibble()
```


```{r}
exp_lvl5 <- exp_lvl5 %>% group_by(Lvl5) %>% mutate(total_umi=sum(Expr_sum_mean),
                                          n_expressed=sum(Expr_sum_mean>0))
exp_lvl5
```

### Scale to 10k molecules

Each cell type is scaled to the same total number of molecules. 

```{R, rm lowQ 34,message=F}
exp_lvl5 <- exp_lvl5 %>% group_by(Lvl5) %>% mutate(Expr_sum_mean_scaled10k=Expr_sum_mean*10000/sum(Expr_sum_mean),
       Expr_sum_mean_scaled1pergene=Expr_sum_mean*n_expressed/sum(Expr_sum_mean))
```

### Check 

```{r}
sumstats_final <- exp_lvl5 %>% group_by(Lvl5) %>% summarise(total_sum_umi_scaled10k=sum(Expr_sum_mean_scaled10k),total_sum_umi_scaled1pergene=sum(Expr_sum_mean_scaled1pergene))
```

```{r}
all.equal(sumstats_final$total_sum_umi_scaled10k,rep(10000,63))
```

### Remove genes not expressed in any tissues

```{r}
g2keep <- exp_lvl5 %>% group_by(Gene) %>% summarise(sum_exp=sum(Expr_sum_mean)) %>% filter(sum_exp>0)
exp_lvl5 <- filter(exp_lvl5,Gene%in%g2keep$Gene)
```

```{r}
exp_lvl5 <- exp_lvl5 %>% group_by(Gene) %>% mutate(spe_10k=Expr_sum_mean_scaled10k/sum(Expr_sum_mean_scaled10k),
                                        spe_1pergene=Expr_sum_mean_scaled1pergene/sum(Expr_sum_mean_scaled1pergene),
                                        ) %>%
  ungroup()
```

```{r}
exp_lvl5 <- exp_lvl5 %>% group_by(Lvl5) %>% mutate(
                    spe_10k_top10=ifelse(spe_10k>=quantile(spe_10k,0.9),1,0),
                    spe_1pergene_top10=ifelse(spe_1pergene>=quantile(spe_1pergene,0.9),1,0),
                    ) %>% ungroup()
```

# Add ENTREZ ID

```{R,message=FALSE}
entrez_ensembl <- AnnotationDbi::toTable(org.Hs.eg.db::org.Hs.egENSEMBL)
entrez_symbol <- AnnotationDbi::toTable(org.Hs.eg.db::org.Hs.egSYMBOL)
entrez_ensembl <- inner_join(entrez_ensembl,entrez_symbol)
```

Only keep genes with a unique entrez and ensembl id.

```{r,message=FALSE}
entrez_ensembl_unique_genes_entrez <- entrez_ensembl %>% count(gene_id) %>% filter(n==1)
entrez_ensembl_unique_genes_ens <- entrez_ensembl %>% count(ensembl_id) %>% filter(n==1)
entrez_ensembl_unique_genes_symbol <- entrez_ensembl %>% count(symbol) %>% filter(n==1)

entrez_ensembl <- filter(entrez_ensembl,gene_id%in%entrez_ensembl_unique_genes_entrez$gene_id & ensembl_id %in% entrez_ensembl_unique_genes_ens$ensembl_id & symbol %in% entrez_ensembl_unique_genes_symbol$symbol)
colnames(entrez_ensembl) <- c("entrez_id","gene_id","Gene")
```

```{r}
exp_lvl5 <- left_join(exp_lvl5,entrez_ensembl,by="Gene")
```

### Write

```{r}
exp_lvl5 <-  select(exp_lvl5,Gene,gene_id,entrez_id,Lvl5,spe_10k) %>% spread(Lvl5,spe_10k)

exp_lvl5 %>% write_tsv(gzfile("../../02_Processed/Habib.norm.txt.gz"))
```
